use common::puzzle::PuzzlePart;

use crate::SecretNumberIterator;

pub struct Puzzle22a {}

impl PuzzlePart for Puzzle22a {
    fn description() -> &'static str {
        "Find the sum of the 2000th numbers generated by a bunch of hashing monkeys."
    }

    fn solve(input: &str) -> String {
        input
            .lines()
            .map(|line| {
                let v = line.parse().unwrap();
                let mut iter = SecretNumberIterator::new(v);
                iter.nth(1999).unwrap()
            })
            .sum::<u64>()
            .to_string()
    }
}
