set shell := ["fish", "-c"]

# `part` can be 'a' or 'b' 
# `arg` can be 'e' for example input
#       or 'r' for release mode
run part="" arg="":
    #!/usr/bin/env fish
    test {{part}} && set part --part {{part}}
    test "{{arg}}" = "e" && set example --example
    test "{{arg}}" = "r" && set release --release
    cargo run --quiet $release -- $part $example

test:
    cargo test
