set shell := ["fish", "-c"]

# `part` can be 'a' or 'b' 
# `arg` can be 'e' for example input
#       or 'r' for release mode
run part="" arg="":
    #!/usr/bin/env fish
    test {{part}} && set part --part {{part}}
    test "{{arg}}" = "e" && set example --example
    test "{{arg}}" = "r" && set release --release
    cargo run --quiet $release -- $part $example
    # copy the result to the clipboard if this was 
    # run on the actual input of just one part
    test {{part}} && test "{{arg}}" != "e" && just copy {{part}} || exit 0

copy part:
    #!/usr/bin/env fish
    ../../setup/copy-soln/copy.fish {{part}}

test:
    cargo test
